### ISSUE TITLE
建议增加存储桶，谢谢

### ISSUE THREAD

**Issue by Raven-Cn** [likeflyme/cloudbak#10]
建议增加存储桶，谢谢
腾讯云COS、阿里云OSS等等

如果用服务器的话，存储是个问题。

**Comment by like-fly** [comment]
暂时不会添加存储桶，这些厂商通常会提供一个工具用于挂载到本地，参考：
https://help.aliyun.com/zh/oss/user-guide/methods-to-attach-an-oss-directory-to-an-ecs-instance

**Comment by like-fly** [comment]
完成关闭
