### ISSUE TITLE
命令行/自动同步

### ISSUE THREAD

**Issue by imlinhanchao** [likeflyme/cloudbak#12]
cloudbak-desktop 是否支持命令行传参自动同步，或是配置定时任务启动同步？

最好希望可以支持命令行，这样可以配合其他定时动作。比如同步完成启动微信之类。

**Comment by like-fly** [comment]
不支持，可以用使用更成熟的工具同步，更方便好用，参考：
https://www.cloudbak.org/advanced/other-sync-tools.html

理论上可以用任意的同步工具同步，甚至自己拷贝文件上去也没问题。

**Comment by imlinhanchao** [comment]
哦~明白了，也就是同步工具其实就是个文件传输软件。我试试。
