### ISSUE TITLE
在“关于我们”有关于"将手机上的数据备份到PC端微信后"相关的描述，但是看不到手机备份的内容

### ISSUE THREAD

**Issue by huahuahuahuahuahuahuahua** [likeflyme/cloudbak#2]
经过我调研后发现这样一种备份的可能，将手机上的数据备份到PC端微信后，用一个备份程序备份到服务器，通过WEB或APP方式访问备份的数据，访问数据还原微信界面和操作逻辑易于使用。所以我花了些时间（其实挺长的）写了这样一个程序，云朵备份。

如上描述，我发现备份过去的内容没有被解析，备份的文件在 BackupFiles 目录下，在代码里面似乎也没有找到处理 BackupFiles 的逻辑。请问这部分逻辑是没有实现吗？还是我的使用姿势有问题

**Comment by like-fly** [comment]
手机微信上不要点备份，要点迁移。迁移是合并数据到电脑微信，备份是打包一份数据到电脑微信目录。

**Comment by huahuahuahuahuahuahuahua** [comment]
原来如此，没咋用过PC微信，感谢
