### ISSUE TITLE
不支持3.9.12.17版本

### ISSUE THREAD

**Issue by qqniubi1705** [likeflyme/cloudbak#8]
![屏幕截图 2024-12-03 203920.png](https://s1.locimg.com/2024/12/03/ad396fce8c555.png)

**Comment by like-fly** [comment]
参考 https://www.cloudbak.org/use/version.html

**Comment by qqniubi1705** [comment]
> 参考 https://www.cloudbak.org/use/version.html

谢谢，没仔细看文档，非常抱歉
